name: "Generate HTML and PDF"
on:
  push:
    branches:
      - master
    paths:
      - flake.*
      - resume.md
      - resume_education.md
      - style.css
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Build Resumes
      run: |
        mkdir out
        nix build
        cp result/resume/resume.html out/${{ github.actor}}_resume.html
        cp result/resume/resume.pdf out/${{ github.actor}}_resume.pdf
        cp result/resume/resume.md out/${{ github.actor}}_resume.md
        cp result/resume_education/resume.html out/${{ github.actor}}_resume_education.html
        cp result/resume_education/resume.pdf out/${{ github.actor}}_resume_education.pdf
        cp result/resume_education/resume.md out/${{ github.actor}}_resume_education.md
    - name: Store Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: resume
        path: out/
  publish:
    runs-on: ubuntu-latest
    needs: generate
    steps:
    - uses: actions/checkout@v4
    - name: Retrieve Artifacts
      uses: actions/download-artifact@v4
      with:
        name: resume
        path: out/
    - name: Stage
      run: |
        mkdir public
        cp out/${{ github.actor }}_resume.html public/index.html
        cp out/${{ github.actor }}_resume_education.html public/education.html
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
    - name: Install hub 
      run: |
        sudo snap install hub --classic
    - name: Set Tag
      id: current-datetime
      run: echo "CURRENT_DATETIME=$(date +'%Y-%m-%d-%H_%M_%S%z')" >> "$GITHUB_OUTPUT"
    - name: Build Release
      shell: bash
      run: |
        hub release create ${{ steps.current-datetime.outputs.CURRENT_DATETIME }} \
        -m ${{ steps.current-datetime.outputs.CURRENT_DATETIME }} \
        -a out/${{ github.actor }}_resume.html \
        -a out/${{ github.actor }}_resume.md \
        -a out/${{ github.actor }}_resume.pdf
        -a out/${{ github.actor }}_resume_education.html \
        -a out/${{ github.actor }}_resume_education.md \
        -a out/${{ github.actor }}_resume_education.pdf
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
